name: 'ASCII Text'
description: 'Display users text with ASCII art'
inputs:
  my-text:
    description: 'Text to convert to ASCII art'
    required: true
    default: 'WOW'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.my-text }}
